<?php
/**
 * src/helpers/adminbackuphelper.php
 * --------------------------------
 * Sauvegarde de la base MySQL via mysqldump.
 */

namespace Biscaphone\Helpers;

class AdminBackupHelper
{
    public static function saveBackup(): string
    {
        $host         = config('database.host', '127.0.0.1');
        $port         = config('database.port', 8889);
        $name         = config('database.name', 'biscaphone');
        $user         = config('database.user', 'root');
        $password     = config('database.password', 'root');
        $mysqldumpBin = config('database.mysqldump_bin', 'mysqldump');

        $backupDir = config('storage.backup_dir');
        if (!is_dir($backupDir)) {
            mkdir($backupDir, 0755, true);
        }

        $filename = 'backup-' . date('Y-m-d-His') . '.sql';
        $filepath = $backupDir . $filename;

        try {
            return self::saveBackupWithMysqldump($host, $port, $name, $user, $password, $mysqldumpBin, $filepath);
        } catch (\RuntimeException $exception) {
            $message = $exception->getMessage();

            if (stripos($message, 'mysql_native_password') !== false
                || stripos($message, 'Authentication plugin') !== false
                || stripos($message, 'cannot be loaded') !== false
            ) {
                return self::saveBackupWithPdo($host, $port, $name, $user, $password, $filepath);
            }

            throw $exception;
        }
    }

    private static function saveBackupWithMysqldump(string $host, int $port, string $name, string $user, string $password, string $mysqldumpBin, string $filepath): string
    {
        $resolvedBin = self::resolveMysqldumpBin($mysqldumpBin);
        $command = sprintf(
            '%s --host=%s --port=%s --user=%s --password=%s %s > %s 2>&1',
            escapeshellarg($resolvedBin),
            escapeshellarg($host),
            escapeshellarg((string) $port),
            escapeshellarg($user),
            escapeshellarg($password),
            escapeshellarg($name),
            escapeshellarg($filepath)
        );

        exec($command, $output, $code);

        if ($code !== 0 || !file_exists($filepath)) {
            $details = implode("\n", $output);
            throw new \RuntimeException('Erreur lors du backup MySQL. mysqldump a échoué. Détails: ' . trim($details));
        }

        return $filepath;
    }

    private static function saveBackupWithPdo(string $host, int $port, string $name, string $user, string $password, string $filepath): string
    {
        $dsn = sprintf('mysql:host=%s;port=%s;dbname=%s;charset=utf8mb4', $host, $port, $name);
        $pdo = new \PDO($dsn, $user, $password, [
            \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
            \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC,
        ]);

        $lines = [];
        $lines[] = '-- Backup generated by BiscaPhone';
        $lines[] = '-- Host: ' . $host;
        $lines[] = '-- Database: ' . $name;
        $lines[] = '-- Date: ' . date('Y-m-d H:i:s');
        $lines[] = '';
        $lines[] = 'SET FOREIGN_KEY_CHECKS = 0;';
        $lines[] = 'SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";';
        $lines[] = 'SET NAMES utf8mb4;';
        $lines[] = '';

        $tables = $pdo->query("SHOW FULL TABLES WHERE Table_Type = 'BASE TABLE'")->fetchAll(\PDO::FETCH_COLUMN);

        foreach ($tables as $table) {
            $escapedTable = str_replace('`', '``', $table);
            $create = $pdo->query('SHOW CREATE TABLE `' . $escapedTable . '`')->fetch(\PDO::FETCH_ASSOC);
            $createSql = $create['Create Table'] ?? null;

            if ($createSql === null) {
                continue;
            }

            $lines[] = 'DROP TABLE IF EXISTS `' . $escapedTable . '`;';
            $lines[] = $createSql . ';';
            $lines[] = '';

            $rows = $pdo->query('SELECT * FROM `' . $escapedTable . '`')->fetchAll();
            if (count($rows) === 0) {
                continue;
            }

            foreach ($rows as $row) {
                $columns = array_map(function ($column) {
                    return '`' . str_replace('`', '``', $column) . '`';
                }, array_keys($row));

                $values = array_map(function ($value) use ($pdo) {
                    if ($value === null) {
                        return 'NULL';
                    }
                    return $pdo->quote((string) $value);
                }, array_values($row));

                $lines[] = 'INSERT INTO `' . $escapedTable . '` (' . implode(', ', $columns) . ') VALUES (' . implode(', ', $values) . ');';
            }

            $lines[] = '';
        }

        $lines[] = 'SET FOREIGN_KEY_CHECKS = 1;';

        file_put_contents($filepath, implode("\n", $lines));

        if (!file_exists($filepath)) {
            throw new \RuntimeException('Impossible de créer le fichier de sauvegarde SQL via PDO.');
        }

        return $filepath;
    }

    public static function downloadBackup(): void
    {
        $filepath = self::saveBackup();
        $filename = basename($filepath);

        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        readfile($filepath);
    }

    private static function resolveMysqldumpBin(string $configured): string
    {
        $candidates = array_filter([
            $configured,
            '/opt/homebrew/bin/mysqldump',
            '/usr/local/bin/mysqldump',
            '/usr/bin/mysqldump',
            '/bin/mysqldump',
            '/usr/local/mysql/bin/mysqldump',
        ]);

        foreach ($candidates as $candidate) {
            if (strpos($candidate, '/') !== false) {
                if (is_executable($candidate)) {
                    return $candidate;
                }
                continue;
            }

            $resolved = trim(shell_exec('command -v ' . escapeshellarg($candidate) . ' 2>/dev/null'));
            if ($resolved !== '') {
                return $resolved;
            }
        }

        throw new \RuntimeException('mysqldump introuvable. Configurez MYSQLDUMP_BIN ou installez mysqldump.');
    }
}
